-- MySQL Script generated by MySQL Workbench
-- 09/24/20 18:10:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parcelamentos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parcelamentos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parcelamentos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `parcelamentos` ;

-- -----------------------------------------------------
-- Table `parcelamentos`.`apikeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcelamentos`.`apikeys` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcelamentos`.`requests_api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcelamentos`.`requests_api` (
  `id` INT NOT NULL,
  `apikeys_id` INT NOT NULL AUTO_INCREMENT,
  `ip_user` TEXT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_requests_api_apikeys_idx` (`apikeys_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_requests_api_apikeys`
    FOREIGN KEY (`apikeys_id`)
    REFERENCES `parcelamentos`.`apikeys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcelamentos`.`taxas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcelamentos`.`taxas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `qtd` INT NULL,
  `taxa` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcelamentos`.`simulacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcelamentos`.`simulacoes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(45) NULL,
  `simulacao` TEXT NULL,
  `opcoes` TEXT NULL,
  `valor_total` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parcelamentos`.`pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcelamentos`.`pagamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `simulacoes_id` INT NOT NULL,
  `sucesso` TINYINT(1) NULL,
  `num_parcelas` INT NULL,
  `data_time` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamentos_simulacoes1_idx` (`simulacoes_id` ASC),
  CONSTRAINT `fk_pagamentos_simulacoes1`
    FOREIGN KEY (`simulacoes_id`)
    REFERENCES `parcelamentos`.`simulacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
